# https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html
cluster.name: docker-cluster
node.name: es01
network.host: 0.0.0.0
cluster.initial_master_nodes: es01

# https://www.elastic.co/guide/en/elasticsearch/reference/current/license-settings.html
xpack.license.self_generated.type: {{ license }}

# https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.key: certs/es01/es01.key
xpack.security.http.ssl.certificate: certs/es01/es01.crt
xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.key: certs/es01/es01.key
xpack.security.transport.ssl.certificate: certs/es01/es01.crt
xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
